// Centralized Mock Data for Jewerkart Luxury Jewellery

export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: 'Kundan Jhumka Earrings',
    slug: 'kundan-jhumka-earrings',
    price: 4999,
    originalPrice: 6999,
    rating: 4.8,
    reviews: 128,
    badge: 'BESTSELLER',
    image: '/category_earrings.jpg',
    images: ['/category_earrings.jpg', '/silver_earrings.jpg'],
    category: 'earrings',
    categoryName: 'Earrings',
    metal: '925',
    metalName: '925 Sterling Silver',
    color: 'gold',
    stone: 'colored zircon',
    stoneName: 'Kundan & Red Zircon',
    style: 'traditional',
    gender: 'women',
    purity: 'BIS Hallmarked 925 Silver with 22K Gold Vermeil',
    description: 'Exquisitely handcrafted traditional Kundan Jhumkas adorned with natural pearl drops and hand-set faceted stones. Perfectly balanced for festive splendour and wedding celebrations.',
    inStock: true,
    sku: 'JK-EAR-001',
    weight: '14.2 gms',
  },
  {
    id: 2,
    name: 'Pearl Drop Danglers',
    slug: 'pearl-drop-danglers',
    price: 3499,
    originalPrice: 4999,
    rating: 4.9,
    reviews: 95,
    badge: 'NEW',
    image: '/silver_earrings.jpg',
    images: ['/silver_earrings.jpg', '/category_earrings.jpg'],
    category: 'earrings',
    categoryName: 'Earrings',
    metal: '925',
    metalName: '925 Sterling Silver',
    color: 'oxidised silver',
    stone: 'pearl',
    stoneName: 'Freshwater Basra Pearl',
    style: 'party',
    gender: 'women',
    purity: 'Pure 925 Sterling Silver',
    description: 'Contemporary chandelier danglers featuring lustrous genuine freshwater pearls mounted on high-polish hypoallergenic 925 sterling silver.',
    inStock: true,
    sku: 'JK-EAR-002',
    weight: '8.6 gms',
  },
  {
    id: 3,
    name: 'Bridal Temple Heritage Necklace',
    slug: 'bridal-temple-heritage-necklace',
    price: 14999,
    originalPrice: 19999,
    rating: 5.0,
    reviews: 234,
    badge: 'BRIDAL',
    image: '/category_necklace.jpg',
    images: ['/category_necklace.jpg', '/silver_necklace.jpg', '/showcase_necklace.jpg'],
    category: 'necklaces',
    categoryName: 'Necklaces',
    metal: '800',
    metalName: '800 Fine Silver with Temple Gold Polish',
    color: 'gold',
    stone: 'colored stone',
    stoneName: 'Burmese Ruby & Emerald Accents',
    style: 'wedding',
    gender: 'women',
    purity: 'Hallmarked 800 Silver with Antique Matte Finish',
    description: 'An ode to ancient South Indian temple jewellery. Hand-carved Lakshmi motifs embraced by cabochon rubies and unblemished South Sea pearls.',
    inStock: true,
    sku: 'JK-NECK-003',
    weight: '48.5 gms',
  },
  {
    id: 4,
    name: 'Solitaire Sparkle Silver Ring',
    slug: 'solitaire-sparkle-silver-ring',
    price: 3999,
    originalPrice: 5499,
    rating: 4.7,
    reviews: 356,
    badge: '925 SILVER',
    image: '/silver_ring.jpg',
    images: ['/silver_ring.jpg', '/category_ring.jpg'],
    category: 'rings',
    categoryName: 'Rings',
    metal: '925',
    metalName: '925 Sterling Silver',
    color: 'oxidised silver',
    stone: 'zircon',
    stoneName: 'Hearts & Arrows 5A Zircon',
    style: 'everyday',
    gender: 'couples',
    purity: 'Rhodium Plated 925 Sterling Silver',
    description: 'A timeless solitaire statement ring featuring a precision-cut 2-carat diamond stimulant set in four platinum-rhodium tipped prongs.',
    inStock: true,
    sku: 'JK-RNG-004',
    weight: '3.8 gms',
  },
  {
    id: 5,
    name: 'Royal Kundan Choker Set',
    slug: 'royal-kundan-choker-set',
    price: 11999,
    originalPrice: 15999,
    rating: 4.9,
    reviews: 182,
    badge: 'TRENDING',
    image: '/silver_necklace.jpg',
    images: ['/silver_necklace.jpg', '/category_necklace.jpg'],
    category: 'necklaces',
    categoryName: 'Necklaces',
    metal: '925',
    metalName: '925 Sterling Silver',
    color: 'gold',
    stone: 'colored stone',
    stoneName: 'Polki Kundan with Tourmaline beads',
    style: 'wedding',
    gender: 'women',
    purity: '22K Gold Plated 925 Hallmarked Silver',
    description: 'A majestic choker ensemble designed to rest regally on your collarbone. Finished with delicate meenakari enamel work on the reverse.',
    inStock: true,
    sku: 'JK-NECK-005',
    weight: '36.2 gms',
  },
  {
    id: 6,
    name: 'Artisan Silver Cuff Bracelet',
    slug: 'artisan-silver-cuff-bracelet',
    price: 4499,
    originalPrice: 5999,
    rating: 4.6,
    reviews: 112,
    badge: '925 SILVER',
    image: '/silver_bracelet.jpg',
    images: ['/silver_bracelet.jpg', '/category_bangle.jpg'],
    category: 'bracelets',
    categoryName: 'Bracelets',
    metal: '925',
    metalName: '925 Sterling Silver',
    color: 'oxidised silver',
    stone: 'colored zircon',
    stoneName: 'Swiss Black Onyx & Clear Zircon',
    style: 'office',
    gender: 'men',
    purity: '925 Solid Sterling Silver with Anti-Tarnish Shield',
    description: 'Sculptural open cuff bracelet crafted for discerning individuals. Features clean architectural bevels and comfortable inner contouring.',
    inStock: true,
    sku: 'JK-BRC-006',
    weight: '22.0 gms',
  },
  {
    id: 7,
    name: 'Imperial Floral Kundan Ring',
    slug: 'imperial-floral-kundan-ring',
    price: 2999,
    originalPrice: 3999,
    rating: 4.8,
    reviews: 89,
    badge: 'BESTSELLER',
    image: '/category_ring.jpg',
    images: ['/category_ring.jpg', '/silver_ring.jpg'],
    category: 'rings',
    categoryName: 'Rings',
    metal: '750',
    metalName: '750 Fine Silver (18K Gold Plated)',
    color: 'gold',
    stone: 'colored zircon',
    stoneName: 'Ruby Red & Polki Kundan',
    style: 'traditional',
    gender: 'women',
    purity: '18K Micro Gold Plated Pure Silver',
    description: 'A striking statement cocktail ring with adjustable comfort band. The floral crown radiates with hand-set Kundan stones.',
    inStock: true,
    sku: 'JK-RNG-007',
    weight: '7.4 gms',
  },
  {
    id: 8,
    name: 'Filigree Gold Kada Bangle',
    slug: 'filigree-gold-kada-bangle',
    price: 8999,
    originalPrice: 11999,
    rating: 4.9,
    reviews: 145,
    badge: 'HEIRLOOM',
    image: '/category_bangle.jpg',
    images: ['/category_bangle.jpg', '/silver_bracelet.jpg'],
    category: 'bangles',
    categoryName: 'Bangles',
    metal: '925',
    metalName: '925 Sterling Silver',
    color: 'gold',
    stone: 'colored stone',
    stoneName: 'Emerald Green Center Stone',
    style: 'traditional',
    gender: 'women',
    purity: '24K Micron Gold Plated 925 Hallmarked Silver',
    description: 'Heirloom filigree openable kada crafted with vintage wirework techniques handed down through generations of Rajasthan artisans.',
    inStock: true,
    sku: 'JK-BNG-008',
    weight: '28.6 gms',
  },
  {
    id: 9,
    name: 'Sacred Bloom Diamond Mangalsutra',
    slug: 'sacred-bloom-diamond-mangalsutra',
    price: 9499,
    originalPrice: 12999,
    rating: 5.0,
    reviews: 310,
    badge: 'BESTSELLER',
    image: '/category_mangalsutra.jpg',
    images: ['/category_mangalsutra.jpg', '/silver_necklace.jpg'],
    category: 'mangalsutra',
    categoryName: 'Mangalsutras',
    metal: '925',
    metalName: '925 Sterling Silver',
    color: 'gold',
    stone: 'zircon',
    stoneName: 'Fine Brilliant Cut Zircons & Black Spinel Beads',
    style: 'everyday',
    gender: 'women',
    purity: 'Hallmarked 925 Silver with Long-Life 22K Micron Gold',
    description: 'An elegant union of sacred heritage and contemporary minimalism. High-grade auspicious black beads strung with a delicate diamond floral pendant.',
    inStock: true,
    sku: 'JK-MNG-009',
    weight: '9.2 gms',
  },
  {
    id: 10,
    name: 'Minimalist Office Gold Chain',
    slug: 'minimalist-office-gold-chain',
    price: 3299,
    originalPrice: 4299,
    rating: 4.6,
    reviews: 74,
    badge: 'OFFICE EDIT',
    image: '/showcase_necklace.jpg',
    images: ['/showcase_necklace.jpg', '/category_necklace.jpg'],
    category: 'necklaces',
    categoryName: 'Necklaces',
    metal: '925',
    metalName: '925 Sterling Silver',
    color: 'gold',
    stone: 'pearl',
    stoneName: 'Single Floating Keshi Pearl',
    style: 'office',
    gender: 'women',
    purity: 'Hypoallergenic 925 Silver with 18K Yellow Gold Dip',
    description: 'Effortless understated sophistication. An ultra-fine link chain suspending an organic baroque freshwater pearl designed for all-day office comfort.',
    inStock: true,
    sku: 'JK-NECK-010',
    weight: '4.5 gms',
  },
  {
    id: 11,
    name: 'Regal Signet Men’s Ring',
    slug: 'regal-signet-mens-ring',
    price: 4199,
    originalPrice: 5699,
    rating: 4.8,
    reviews: 62,
    badge: 'FOR HIM',
    image: '/silver_ring.jpg',
    images: ['/silver_ring.jpg'],
    category: 'rings',
    categoryName: 'Rings',
    metal: '925',
    metalName: '925 Sterling Silver',
    color: 'oxidised silver',
    stone: 'colored stone',
    stoneName: 'Natural Star Diopside Black Gem',
    style: 'everyday',
    gender: 'men',
    purity: 'Solid 925 Hallmark Silver (Heavy Gauge)',
    description: 'A commanding signet ring boasting a brushed satin crown and mirror-polished shanks. Engineered for durable daily wear.',
    inStock: true,
    sku: 'JK-RNG-011',
    weight: '12.4 gms',
  },
  {
    id: 12,
    name: 'Gilded Twilight Stud Earrings',
    slug: 'gilded-twilight-stud-earrings',
    price: 2499,
    originalPrice: 3299,
    rating: 4.7,
    reviews: 140,
    badge: 'NEW',
    image: '/category_earrings.jpg',
    images: ['/category_earrings.jpg'],
    category: 'earrings',
    categoryName: 'Earrings',
    metal: '750',
    metalName: '750 Silver',
    color: 'gold',
    stone: 'colored zircon',
    stoneName: 'Sapphire Blue Zircon',
    style: 'everyday',
    gender: 'kids',
    purity: 'Nickel-Free & Lead-Free 750 Silver',
    description: 'Delicate celestial starburst studs featuring sparkling sapphire blue centers. Hypoallergenic screw backs suitable for sensitive ears.',
    inStock: true,
    sku: 'JK-EAR-012',
    weight: '2.8 gms',
  }
];

export const MOCK_CATEGORIES = [
  {
    name: 'Earrings',
    slug: 'earrings',
    image: '/category_earrings.jpg',
    itemCount: 48,
    description: 'From majestic jhumkas and chandeliers to minimal everyday studs.',
  },
  {
    name: 'Necklaces & Chokers',
    slug: 'necklaces',
    image: '/category_necklace.jpg',
    itemCount: 36,
    description: 'Artisanal temple necklaces, heirloom chokers, and delicate pendants.',
  },
  {
    name: 'Rings & Bands',
    slug: 'rings',
    image: '/category_ring.jpg',
    itemCount: 52,
    description: 'Solitaire rings, cocktail Kundan bands, and men’s signet creations.',
  },
  {
    name: 'Bangles & Kadas',
    slug: 'bangles',
    image: '/category_bangle.jpg',
    itemCount: 24,
    description: 'Intricately chased kadas, filigree bangles, and gemstone cuffs.',
  },
  {
    name: 'Bracelets',
    slug: 'bracelets',
    image: '/silver_bracelet.jpg',
    itemCount: 30,
    description: 'Tennis charm bracelets, adjustable links, and statement cuffs.',
  },
  {
    name: 'Mangalsutras',
    slug: 'mangalsutra',
    image: '/category_mangalsutra.jpg',
    itemCount: 18,
    description: 'Sacred modern iterations designed for daily grace and comfort.',
  }
];

export const MOCK_COLLECTIONS = [
  {
    name: 'Royal Heritage Edit',
    slug: 'royal-heritage',
    image: '/showcase_necklace.jpg',
    tagline: 'Centuries of Rajputana Grandeur',
    description: 'Handcrafted temple and Kundan jewellery inspired by royal dynasties of Rajasthan. Accented with Basra pearls and uncut gemstones.',
    badge: 'ROYAL ATELIER',
    itemCount: 24,
  },
  {
    name: 'Solitaire & 925 Pure Silver',
    slug: 'pure-silver-solitaire',
    image: '/silver_ring.jpg',
    tagline: 'Modern Geometric Radiance',
    description: 'Hypoallergenic 925 sterling silver plated with mirror-like platinum rhodium and set with 5A flawless diamond stimulants.',
    badge: 'SIGNATURE 925',
    itemCount: 32,
  },
  {
    name: 'Bridal Symphony',
    slug: 'bridal-symphony',
    image: '/category_necklace.jpg',
    tagline: 'The Ultimate Heirloom Trousseau',
    description: 'Magnificent bridal choker sets, hathphools, maang tikkas, and jhumkas curated for the discerning Indian bride.',
    badge: 'BRIDAL EXCLUSIVE',
    itemCount: 18,
  },
  {
    name: 'Everyday Minimalist Elegance',
    slug: 'everyday-minimalist',
    image: '/silver_bracelet.jpg',
    tagline: 'Subtle Luxury For Modern Living',
    description: 'Feather-light chains, delicate huggie hoops, and stackable rings thoughtfully created for work, brunch, and travel.',
    badge: 'DAILY ESSENTIALS',
    itemCount: 40,
  }
];

export const MOCK_ORDERS = [
  {
    orderId: 'JK-2026-894215',
    date: 'Sep 24, 2026',
    status: 'In Transit',
    statusColor: '#C5914A',
    courier: 'Sequel Armored Logistics (BlueDart Express)',
    trackingNumber: 'BLUEDART-SEC-9928174',
    estimatedDelivery: 'Sep 28, 2026',
    total: 17998,
    items: [
      {
        id: 1,
        name: 'Kundan Jhumka Earrings',
        purity: '925 Sterling Silver • 22K Gold Vermeil',
        price: 4999,
        quantity: 1,
        image: '/category_earrings.jpg',
      },
      {
        id: 3,
        name: 'Bridal Temple Heritage Necklace',
        purity: '800 Fine Silver with Temple Gold Polish',
        price: 12999,
        quantity: 1,
        image: '/category_necklace.jpg',
      }
    ],
    shippingAddress: {
      fullName: 'Priya Sharma',
      phone: '+91 98765 43210',
      address: 'Flat 402, Royale Meadows, 14th Cross, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
    }
  },
  {
    orderId: 'JK-2026-881204',
    date: 'Aug 18, 2026',
    status: 'Delivered',
    statusColor: '#16a34a',
    courier: 'Sequel Armored Logistics',
    trackingNumber: 'SEQ-ARM-448102',
    estimatedDelivery: 'Aug 21, 2026',
    total: 3999,
    items: [
      {
        id: 4,
        name: 'Solitaire Sparkle Silver Ring',
        purity: 'Rhodium Plated 925 Sterling Silver',
        price: 3999,
        quantity: 1,
        image: '/silver_ring.jpg',
      }
    ],
    shippingAddress: {
      fullName: 'Priya Sharma',
      phone: '+91 98765 43210',
      address: 'Flat 402, Royale Meadows, 14th Cross, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
    }
  }
];
